// Map common categories to Heroicon component names (from @heroicons/react/24/outline)
export const CATEGORY_ICONS: Record<string, string> = {
  'Electronics': 'ComputerDesktopIcon',
  'Fashion': 'ShoppingBagIcon',
  'Sports': 'TrophyIcon',
  'Home': 'HomeIcon',
  'Beauty': 'SparklesIcon',
  'Travel': 'GlobeAltIcon',
  'Food': 'ShoppingCartIcon',
  'Gaming': 'CpuChipIcon',
  'Toys': 'GiftIcon',
  'Books': 'BookOpenIcon',
  'Clothing': 'ShoppingBagIcon',
  'Shoes': 'ShoppingBagIcon',
  'Accessories': 'SparklesIcon',
  'Outdoors': 'SunIcon',
  'Appliances': 'WrenchScrewdriverIcon',
  'Furniture': 'HomeIcon',
  'Garden': 'BeakerIcon',
  'Automotive': 'WrenchScrewdriverIcon',
  'Health': 'HeartIcon',
  'Kids': 'GiftIcon',
  'Baby': 'GiftIcon',
  'Pet': 'HeartIcon',
  'Music': 'MusicalNoteIcon',
  'Tools': 'WrenchScrewdriverIcon',
  'Office': 'BriefcaseIcon',
  'Cameras': 'CameraIcon',
  'Phones': 'DevicePhoneMobileIcon',
  'Watches': 'ClockIcon',
  'Jewellery': 'SparklesIcon',
  'Groceries': 'ShoppingCartIcon',
  'Toys & Games': 'PuzzlePieceIcon',
  'Art & Craft': 'PaintBrushIcon',
  'Fitness': 'TrophyIcon',
};

import {
  ComputerDesktopIcon,
  ShoppingBagIcon,
  TrophyIcon,
  HomeIcon,
  SparklesIcon,
  GlobeAltIcon,
  ShoppingCartIcon,
  CpuChipIcon,
  GiftIcon,
  BookOpenIcon,
  TagIcon,
  SunIcon,
  WrenchScrewdriverIcon,
  BeakerIcon,
  HeartIcon,
  MusicalNoteIcon,
  BriefcaseIcon,
  CameraIcon,
  DevicePhoneMobileIcon,
  ClockIcon,
  PuzzlePieceIcon,
  PaintBrushIcon,
} from '@heroicons/react/24/outline';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type IconComponent = React.ComponentType<any>;

const ICON_MAP: Record<string, IconComponent> = {
  ComputerDesktopIcon,
  ShoppingBagIcon,
  TrophyIcon,
  HomeIcon,
  SparklesIcon,
  GlobeAltIcon,
  ShoppingCartIcon,
  CpuChipIcon,
  GiftIcon,
  BookOpenIcon,
  SunIcon,
  WrenchScrewdriverIcon,
  BeakerIcon,
  HeartIcon,
  MusicalNoteIcon,
  BriefcaseIcon,
  CameraIcon,
  DevicePhoneMobileIcon,
  ClockIcon,
  PuzzlePieceIcon,
  PaintBrushIcon,
};

export function getCategoryIcon(category: string): IconComponent {
  const name = CATEGORY_ICONS[category];
  return (name ? ICON_MAP[name] : null) || TagIcon;
}
